# Generated by Django 2.0.1 on 2018-01-24 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='English',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('txt', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'english',
            },
        ),
        migrations.CreateModel(
            name='Enlv',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('en', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='translations.English')),
            ],
            options={
                'db_table': 'enlv',
            },
        ),
        migrations.CreateModel(
            name='Latvian',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('txt', models.TextField(unique=True)),
                ('alt', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'latvian',
            },
        ),
        migrations.AddField(
            model_name='enlv',
            name='lv',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='translations.Latvian'),
        ),
    ]
