# Generated by Django 2.0.1 on 2018-01-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='English',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('txt', models.TextField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'english',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EnLv',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'en_lv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Latvian',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('txt', models.TextField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'latvian',
                'managed': False,
            },
        ),
    ]
